### ISSUE TITLE
Dependency bumps

### ISSUE THREAD

**Issue by georgefst** [alexkazik/qrcode#3]
`qrcode-core` and `qrcode-juicypixels` both build with `bytestring-0.11.1.0`, at least on my x86_64 Linux machine. It would be great if you could increase the version bounds in the cabal file to reflect this.

**Comment by alexkazik** [comment]
I'm going to test it (probably in a few days), and when everything works as expected I'll release it.

**Comment by alexkazik** [comment]
It's released - have fun with it.
