### ISSUE TITLE
Text 2.0

### ISSUE THREAD

**Issue by georgefst** [alexkazik/qrcode#4]
Dependency bounds need loosening to allow `text-2.0`, which ships with GHC 9.4. No code changes appear to be needed. (I haven't opened a PR myself since I don't use Stack, so there are one or two details I'm unsure of.)

**Comment by alexkazik** [comment]
I've just fixed that and uploaded new versions.

BTW: A PR is not that hard, just look at the few last commits.

**Comment by georgefst** [comment]
Thanks!
